## 4-е домашнее задание - Библиотека numpy

Подпишите этот блокнот: укажите ФИО и номер группы. Выполненное задание загрузите в свой репозиторий «<b>Spring2023Python</b>» в github в папку "<b>homework04</b>".  

Перед выполнением этого домашнего задания полезно прочитать про возможности и основные методы библиотеки numpy:  
http://acm.mipt.ru/twiki/bin/view/Cintro/PythonNumpy  


In [2]:
import numpy as np

1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [3]:
interval = np.linspace(-1.3, 2.5, 65)
print(interval)

[-1.3      -1.240625 -1.18125  -1.121875 -1.0625   -1.003125 -0.94375
 -0.884375 -0.825    -0.765625 -0.70625  -0.646875 -0.5875   -0.528125
 -0.46875  -0.409375 -0.35     -0.290625 -0.23125  -0.171875 -0.1125
 -0.053125  0.00625   0.065625  0.125     0.184375  0.24375   0.303125
  0.3625    0.421875  0.48125   0.540625  0.6       0.659375  0.71875
  0.778125  0.8375    0.896875  0.95625   1.015625  1.075     1.134375
  1.19375   1.253125  1.3125    1.371875  1.43125   1.490625  1.55
  1.609375  1.66875   1.728125  1.7875    1.846875  1.90625   1.965625
  2.025     2.084375  2.14375   2.203125  2.2625    2.321875  2.38125
  2.440625  2.5     ]


2.	Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [11]:
n = 10
arr = np.array([i % 3 + 1 for i in range(n)])
print(arr)

[1 2 3 1 2 3 1 2 3 1]


3.	Создайте массив первых 10 нечетных целых чисел.

In [13]:
n = 10
arr = np.array([i for i in range(1, n * 2, 2)])
print(arr)

[ 1  3  5  7  9 11 13 15 17 19]


4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [6]:
n = 10
arr = np.zeros((n, n))
arr[0, 0] = arr[0, n-1] = arr[n-1, 0] = arr[n-1, n-1] = 1
print(arr)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [7]:
n = 8
arr = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        if (i + j) % 2 == 0:
            arr[i][j] = 0
        else:
            arr[i][j] = 1
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [8]:
n = 8
arr = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        arr[i][j] = i + j
print(arr)

[[ 0.  1.  2.  3.  4.  5.  6.  7.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.]
 [ 2.  3.  4.  5.  6.  7.  8.  9.]
 [ 3.  4.  5.  6.  7.  8.  9. 10.]
 [ 4.  5.  6.  7.  8.  9. 10. 11.]
 [ 5.  6.  7.  8.  9. 10. 11. 12.]
 [ 6.  7.  8.  9. 10. 11. 12. 13.]
 [ 7.  8.  9. 10. 11. 12. 13. 14.]]


7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [9]:
matrix1 = np.array([[1,2,3],[2,3,4],[4,5,6]])
matrix2 = np.array([[1,2,3],[2,3,4],[4,5,6]])
vec1 = np.array([1, 2, 3])
vec2 = np.array([[1],[2],[3]])
print(np.dot(vec1, vec2))
print(np.dot(matrix1, vec2))
print(np.dot(matrix1, matrix2))

[14]
[[14]
 [20]
 [32]]
[[17 23 29]
 [24 33 42]
 [38 53 68]]


8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [10]:
OX = np.linspace(0, 1, 21)
OCOS = np.cos(OX)
OSIN = np.sin(OX)
print(np.array2string(OCOS))

[1.         0.99875026 0.99500417 0.98877108 0.98006658 0.96891242
 0.95533649 0.93937271 0.92106099 0.9004471  0.87758256 0.85252452
 0.82533561 0.7960838  0.76484219 0.73168887 0.69670671 0.65998315
 0.62160997 0.58168309 0.54030231]


9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [65]:
A = np.random.rand(3, 5) * 4 - 1
print(A)

[[ 2.17049139  2.51961305  0.55536444  2.3929117  -0.14572731]
 [-0.83552503 -0.93853008  2.45931005  1.70505535  1.79697355]
 [ 1.98479198 -0.17054013  0.06994364  2.09542253 -0.91448014]]


10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [66]:
print(np.sum(A))
print(np.sum(A, axis=0))
print(np.sum(A, axis=1))
print()
for row in A:
    print("Строка", row, "Ср знач", np.average(row), "Дисперсия дед инсайд", np.var(row), "Отклон", np.std(row))
    print()

14.745074995491668
[3.31975835 1.41054284 3.08461813 6.19338958 0.7367661 ]
[7.49265327 4.18728383 3.06513789]

Строка [ 2.17049139  2.51961305  0.55536444  2.3929117  -0.14572731] Ср знач 1.4985306547874422 Дисперсия дед инсайд 1.1774409460543809 Отклон 1.0850995097475535

Строка [-0.83552503 -0.93853008  2.45931005  1.70505535  1.79697355] Ср знач 0.8374567664297597 Дисперсия дед инсайд 2.0513610383962884 Отклон 1.4322573226890092

Строка [ 1.98479198 -0.17054013  0.06994364  2.09542253 -0.91448014] Ср знач 0.6130275778811306 Дисперсия дед инсайд 1.4642861379656769 Отклон 1.2100769140702077



11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [67]:
for i in range(3):
    avg = np.average(A[i])
    sd = np.std(A[i])
    A[i] = (A[i] - avg) / sd
print(A)

[[ 0.61926186  0.94100346 -0.8691979   0.82423873 -1.51530616]
 [-1.16807348 -1.23999146  1.13237562  0.60575608  0.66993324]
 [ 1.13361753 -0.64753546 -0.44880117  1.22504192 -1.26232283]]


12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [69]:
col = A[:,2]
inds = np.argsort(col)
B = A.copy()
A[0], A[1], A[2] = B[inds[0]], B[inds[1]], B[inds[2]]
print(A)

[-0.8691979  -0.44880117  1.13237562]
[0 1 2]
[[ 0.61926186  0.94100346 -0.8691979   0.82423873 -1.51530616]
 [ 1.13361753 -0.64753546 -0.44880117  1.22504192 -1.26232283]
 [-1.16807348 -1.23999146  1.13237562  0.60575608  0.66993324]]


13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [70]:
B = A.transpose().dot(A)
C = A.dot(A.transpose())
print(B)
print(C)

[[ 3.03296961  1.29707115 -2.36972792  1.191581   -3.15189384]
 [ 1.29707115  2.84236851 -1.93143967 -0.76877894 -1.43922105]
 [-2.36972792 -1.93143967  2.23920203 -0.5802834   2.64224896]
 [ 1.191581   -0.76877894 -0.5802834   2.54703763 -2.38955628]
 [-3.15189384 -1.43922105  2.64224896 -2.38955628  4.33842222]]
[[ 5.          3.40530259 -3.39030446]
 [ 3.40530259  5.         -1.13301707]
 [-3.39030446 -1.13301707  5.        ]]


Матрицы красивые. Первая матрица 5 на 5, вторая - 3 на 3. Сходство: матрицы квадратные. Различие: матрицы разных размеров

14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [75]:
print(np.sum(B.diagonal()) + np.sum(C.diagonal()))

[3.03296961 2.84236851 2.23920203 2.54703763 4.33842222]
14.999999999999996
29.999999999999996


15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg). 


In [83]:
print(np.linalg.det(B))
print(np.linalg.det(C))
print(np.linalg.matrix_rank(A))
print(np.linalg.matrix_rank(B))
print(np.linalg.matrix_rank(C))
print(np.linalg.eig(B)[0])
print(np.linalg.eig(C)[0])

-1.1971085926249535e-30
29.29150400030825
3
3
3
[ 1.04050148e+01  3.86699535e+00  7.27989841e-01  2.79661582e-16
 -2.67876770e-16]
[10.40501481  0.72798984  3.86699535]


16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять два из следующих примеров:  
- один с номером, сгенерированным случайным образом с помощью функции np.random.randint(9), в качестве seed для генератора случайных чисел взять номер своего студенческого билета. 
- второй номер - под номером 9, несобственный интерграл. Подумайте, как сделать подбор шага интегрирования адаптивным.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        <td> 9) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        </tr>
</table>

## Генерируем вариант

In [87]:
np.random.seed(1032201716)
print(np.random.randint(9))

6


## Решаем интеграл

In [113]:
def f(x):
    return np.cosh(3 * x)**2
def rect(OX, dx, N):
    return dx * np.sum(f(OX))
def trapz(OX, dx, N):
    return dx/2 * (f(OX[0]) + 2*np.sum(f(OX[1:N-1])) + f(OX[N-1]))
def symp(OX, dx, N):
    return dx/3 * (f(OX[0]) + 2*np.sum(f(OX[2:N-1:2])) + 4*np.sum(f(OX[1:N-1:2])) + f(OX[N-1]))
rval = 1
tval = 2
sval = 3
eps = 10**(-5)
N = 2
a = 0
b = 1/3
while np.abs((rval - tval)) > eps or np.abs((tval - sval)) > eps or np.abs((rval - sval)) > eps:
    OX = np.linspace(a, b, N+1)
    dx = (b-a)/N
    rval = rect(OX, dx, N+1)
    tval = trapz(OX, dx, N+1)
    sval = symp(OX, dx, N+1)
    #print(rval, tval, sval)
    N *= 2
print(N)
print(rval, tval, sval)
print("Значение, полученное аналитически:", 0.4689050339872516)

131072
0.4689136325871791 0.46890503401070827 0.4689050339872516
Значение, полученное аналитически: 0.4689050339872516


## Решаем жуткий интеграл

In [118]:
def f(x):
    return (2 + 3*x - 2*x**2)**(-1/2)
N = 1310272
a = 1.5
b = 2 - eps # в точке b деление на ноль
dx = (b-a)/N
OX = np.linspace(a, b, N+1)
print(symp(OX, dx, N+1))

0.6528683078315729
